### PR TITLE
Add a .travis.yml using shellcheck to lint our files

### PR DESCRIPTION
**Pull request by GLolol**
Travis CI is a continuous integration platform that hooks onto Git commits and can automatically compile/test/do whatever with code as commits are pushed to a repository: http://docs.travis-ci.com/user/for-beginners/

In this case, I've added a `.travis.yml` (Travis configuration) file that automatically downloads and runs `shellcheck` on `rlw`, with (and without, for reference) the applicable exceptions to prevent false positives.

@alfonsojon I will have to enable Travis for this repository manually if this gets merged. Afterwards, results will be available at https://travis-ci.org/roblox-linux-wrapper/roblox-linux-wrapper. I've already [enabled it for my fork](https://travis-ci.org/GLolol/roblox-linux-wrapper) so you can see it in action.

### CODE REVIEW

**Comment by alfonsojon** [comment]
Very exciting - taking a look at your fork right now.

**Comment by alfonsojon** [comment]
I've authorized the roblox-linux-wrapper organization Travis access

**Comment by GLolol** [comment]
Okay, I've enabled travis for this repository: https://travis-ci.org/roblox-linux-wrapper/roblox-linux-wrapper

**Comment by alfonsojon** [comment]
Fantastic, thanks.

**Pull request merged**
