### PR TITLE
Fix winetricks "command not found" errors

### PR DESCRIPTION
**Pull request by Abequinn**
Assuming if you already did "chmod +x winetricks"

### CODE REVIEW

**Comment by GLolol** [comment]
Is this even correct? The only time where `./winetricks` would make sense is if it's in the same folder as rlw, and that would only realistically happen in places like `/usr/bin`. However, those folders should be in the PATH anyways, and a system wide installation of programs should always be `+x` already unless you did something horribly wrong...

Please explain in more detail what error you're actually trying to fix.

**Comment by Abequinn** [comment]
When I cloned this repo, and I ran it, it showed with
```
Winetricks: Error: Command not found
``` 
or something similar

**Comment by Abequinn** [comment]
Also, in the regular deb file, there is a copy of wine tricks in the folder

**Comment by GLolol** [comment]
You have to install winetricks, either from your system repository (`apt-get install winetricks`) or to somewhere in PATH; the latest rlw .debs (from my apt repo) no longer bundle a copy of winetricks.

I've gone ahead and removed the .deb's from the releases page as the old versions are all broken and can't even start the game anymore.

**Pull request closed without merging**
