### PR TITLE
Introduce Roblox protocols handlers, fix studio location and more

### PR DESCRIPTION
**Pull request by KrystianoXPL**
I have made a couple of changes and fixes to rlw, and also added protocols handlers for roblox-player and roblox-studio, so you can launch them from website. I did some tests and checks but there may be still some errors, some of those additions probably need some improvements for example installing protocols in deb script.

### CODE REVIEW

**Comment by alfonsojon** [comment]
Nice! I'm curious to know, does it forward the login information? I don't want players to log in as a guest. @KrystianoXPL

**Comment by KrystianoXPL** [comment]
Yes it does! I looked at the user list before the game shutdown.

**Comment by alfonsojon** [comment]
@KrystianoXPL Glad to hear. I'll test this change out, then merge if it works. Thank you for the contribution!

**Comment by KrystianoXPL** [comment]
Ok Thanks!

**Comment by alfonsojon** [comment]
Update: I saw in one commit that it only works with Chromium browsers. I tested on Ubuntu 16.04, and Firefox was able to successfully launch a game, and even have me be logged in.

**Comment by GLolol** [comment]
Some notes (disclaimer: I have not tried this on my system yet):

1) Instead of sourcing `vars.sh` which duplicates a bunch of `rlw` code, would it be better to just break up `rlw` into a subscript that gets sourced by both the launchers and `rlw` instead?
2) Packaging would require not fixing the Roblox launchers' paths to `$HOME/.rlw` - it's preferable to name them simply `roblox-player` and `roblox-studio` (no .sh extension), so they can be dropped into `/usr/bin` or anywhere the user's PATH. Then, the desktop files can easily point to just the program name, while the scripts should source `vars.sh` or whatever shared subscript by looking at `$WRAPPER_DIR`.
    - Specifically, if `"$WRAPPER_DIR" == "/usr/bin"`, the shared subscript should be in `/usr/lib/roblox-linux-wrapper/`, and otherwise in the main script directory.
    - In the long run, it's probably better to redo the build system (Makefile-style?) so that the user has more flexibility on where to put things. Paths like `/usr/local/bin` + `/usr/local/lib` should be supported following the [FHS spec](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) but aren't yet.
3) The `RobloxProxy.dll` override in [`playerwrapper()`](https://github.com/roblox-linux-wrapper/roblox-linux-wrapper/blob/master/rlw#L157-L173) should probably be dropped as it is obsolete.

I think now would be a good time to rethink how complex the script should be, and rewrite/remove the parts that aren't needed. What exactly is needed now to run the game besides installing Roblox from the official site and registering its protocols? If the installer runs fine with stock Wine, a wrapper to download and run it really isn't necessary.

**Comment by alfonsojon** [comment]
You do have a very good point. Perhaps I should rewrite the script?

**Comment by GLolol** [comment]
I'd consider it, but it's better to review what's needed and what isn't first.

**Comment by alfonsojon** [comment]
Right. I'll open a new issue for this.

**Comment by KrystianoXPL** [comment]
Yeah it would be a good idea. I can not know where the user hold the main script I could use find but I prefer to not. So copying part of the script seemed like the only solution.

**Pull request merged**
